"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ImageFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    timestamp: builtins.int
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["image_data", b"image_data", "timestamp", b"timestamp"]) -> None: ...

global___ImageFrame = ImageFrame

@typing.final
class BoundingBox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    XMIN_FIELD_NUMBER: builtins.int
    YMIN_FIELD_NUMBER: builtins.int
    XMAX_FIELD_NUMBER: builtins.int
    YMAX_FIELD_NUMBER: builtins.int
    xmin: builtins.float
    ymin: builtins.float
    xmax: builtins.float
    ymax: builtins.float
    def __init__(
        self,
        *,
        xmin: builtins.float = ...,
        ymin: builtins.float = ...,
        xmax: builtins.float = ...,
        ymax: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["xmax", b"xmax", "xmin", b"xmin", "ymax", b"ymax", "ymin", b"ymin"]) -> None: ...

global___BoundingBox = BoundingBox

@typing.final
class DetectedObject(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLASS_NAME_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    BBOX_FIELD_NUMBER: builtins.int
    class_name: builtins.str
    confidence: builtins.float
    @property
    def bbox(self) -> global___BoundingBox: ...
    def __init__(
        self,
        *,
        class_name: builtins.str = ...,
        confidence: builtins.float = ...,
        bbox: global___BoundingBox | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bbox", b"bbox"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bbox", b"bbox", "class_name", b"class_name", "confidence", b"confidence"]) -> None: ...

global___DetectedObject = DetectedObject

@typing.final
class DetectionResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECTS_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DetectedObject]: ...
    def __init__(
        self,
        *,
        objects: collections.abc.Iterable[global___DetectedObject] | None = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["objects", b"objects", "timestamp", b"timestamp"]) -> None: ...

global___DetectionResult = DetectionResult
