# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cvengine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cvengine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63vengine.proto\x12\x08\x63vengine\"3\n\nImageFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"E\n\x0b\x42oundingBox\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\"]\n\x0e\x44\x65tectedObject\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12#\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x15.cvengine.BoundingBox\"O\n\x0f\x44\x65tectionResult\x12)\n\x07objects\x18\x01 \x03(\x0b\x32\x18.cvengine.DetectedObject\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32W\n\x0f\x43VEngineService\x12\x44\n\rDetectObjects\x12\x14.cvengine.ImageFrame\x1a\x19.cvengine.DetectionResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cvengine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEFRAME']._serialized_start=28
  _globals['_IMAGEFRAME']._serialized_end=79
  _globals['_BOUNDINGBOX']._serialized_start=81
  _globals['_BOUNDINGBOX']._serialized_end=150
  _globals['_DETECTEDOBJECT']._serialized_start=152
  _globals['_DETECTEDOBJECT']._serialized_end=245
  _globals['_DETECTIONRESULT']._serialized_start=247
  _globals['_DETECTIONRESULT']._serialized_end=326
  _globals['_CVENGINESERVICE']._serialized_start=328
  _globals['_CVENGINESERVICE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
